fix: hub_client refresh_component_access_token
edragonconnect/elixir_wechat pull request #11
Opened 2022-11-21 09:46 UTC by feng19

notice hub to refresh_component_access_token when hub_client token expired.

In special scenarios, the component_access_token may expire prematurely, 
but the hub fails to handle it in time. 

Therefore, a mechanism is added to let the hub_client role notify the hub to determine whether it has timed out after the hub receives the request. 
If it has timed out, it will be refreshed and return the latest token.

2022-11-21 10:10 UTC, sumioo commented on lib/plug/refresh_component_access_token.ex
> +      token = WeChat.Component.fetch_component_access_token(appid, comp_adapter_storage)
"token" and "access_token" may be not the same

2022-11-21 10:48 UTC, feng19 commented on lib/plug/refresh_component_access_token.ex
> +      token = WeChat.Component.fetch_component_access_token(appid, comp_adapter_storage)
I don't understand what you mean, Can explain in detail ??

2022-11-22 03:00 UTC, xosdy requested changes

2022-11-22 03:00 UTC, xosdy commented on lib/plug/refresh_component_access_token.ex
> +    defp refresh(_, _) do
change to clearer function name

```suggestion
          case refresh_if_expired(body, adapter_storage) do
            {:ok, token} ->
              %{
                "access_token" => token.access_token,
                "expires_in" => token.expires_in,
                "timestamp" => token.timestamp
              }

            {:error, %WeChat.Error{} = error} ->
              Logger.error(
                "fetch access token occurs an error: #{inspect(error)} with body params: #{inspect(body)}"
              )

              error
          end
        rescue
          error in WeChat.Error ->
            error
        end

      conn
      |> put_resp_content_type("application/json")
      |> send_resp(200, Jason.encode!(result))
      |> halt()
    end

    defp refresh_if_expired(%{"appid" => appid, "access_token" => access_token}, adapter_storage) do
      comp_adapter_storage = adapter_storage[:component]
      token = WeChat.Component.fetch_component_access_token(appid, comp_adapter_storage)

      with {:ok, %{access_token: ^access_token}} <- token,
           true <- token_expired?(access_token) do
        adapter_storage.refresh_component_access_token(appid, access_token, nil)
      else
        false -> token
        _ -> token
      end
    end

    defp refresh_if_expired(_, _) do
```

2022-11-22 03:51 UTC, xinz commented on lib/plug/refresh_component_access_token.ex
> +      token = WeChat.Component.fetch_component_access_token(appid, comp_adapter_storage)
代码中的参数`token`来自远端从hub中获取到的access token，而当下的参数`access_token`是这会请求时已经发现需要刷新操作的access token，所以 @sumioo 会提出这会它们此时已经不一样了。考虑到这里在下面会重新请求hub重新刷新access token，这里L44请求`token`可能又会被失效。 @feng19 @sumioo 你们怎么看？

2022-11-22 03:53 UTC, xinz commented on lib/plug/refresh_component_access_token.ex
> +           true <- token_expired?(access_token) do
这里`token_expired?/1`再次专门发起一个特定接口查询以论证access token的有效性，这个方式似乎不用，直接请求远程hub进行刷新就好（`adapter_storage.refresh_component_access_token`），因为来到这里的上下文说明此刻在client端的access token已过期。

2022-11-22 03:53 UTC, xinz commented on lib/plug/refresh_component_access_token.ex
> +           true <- token_expired?(access_token) do
@feng19 @xosdy @sumioo 请看看

2022-11-22 03:58 UTC, feng19 commented on lib/plug/refresh_component_access_token.ex
> +           true <- token_expired?(access_token) do
ok， 我修改一下，这里前提是 client 是完全可信赖的。

2022-11-22 04:00 UTC, xinz commented on lib/plug/refresh_component_access_token.ex
> +           true <- token_expired?(access_token) do
是的有这个预设

2022-11-22 04:11 UTC, merged